---
- name: Modulo de Instalación de Erratas Full
  hosts: all
  become: true
  tasks:
  - name: Instalacion de Erratas Full
    ansible.builtin.yum:
      name: '*'
      state: latest
      update_cache: yes
  - name: Reboot post-instalar erratas full
    reboot:
        reboot_timeout: 460055

